apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: t2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: deploy
                operator: In
                values:
                - nexus
      containers:
      - image: 3.89.70.197:32002/jenkins-example:4
        name: java-app
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-auth
