apiVersion: v1
kind: Service
metadata:
  name: javaservice
  namespace: t2  
 
spec:
  clusterIP: 172.20.225.221
  clusterIPs:
  - 172.20.225.221
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31000
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: javaApp
  type: NodePort
